### ISSUE TITLE
still pulling etcd image from gcr.io

### ISSUE THREAD

**Issue by pahud** [pahud/kops-bjs#9]
as title

**Comment by pahud** [comment]
example for `ZHY` region.
```
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-cn-northwest-1a
      name: a
    - instanceGroup: master-cn-northwest-1b
      name: b
    - instanceGroup: master-cn-northwest-1c
      name: c
    image: anjia0532/etcd:2.2.1
    name: main
  - etcdMembers:
    - instanceGroup: master-cn-northwest-1a
      name: a
    - instanceGroup: master-cn-northwest-1b
      name: b
    - instanceGroup: master-cn-northwest-1c
      name: c
    image: anjia0532/etcd:2.2.1
    name: events
```
